name: furnish_x
description: furniture design and orders

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  motion_tab_bar_v2:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/resources/images/

  fonts:
    - family: Sebino
      fonts:
        - asset: lib/resources/fonts/Sebino-Bold.ttf
